import type { Metadata } from 'next';

import { LegalPage } from '@/components/legal/legal-page';
import { legalConfig } from '@/lib/legal-config';

export const metadata: Metadata = {
  title: 'Privacy Policy | Threadmap',
  description: 'How Threadmap collects, uses, protects, and deletes personal data.',
};

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="Your data" title="Privacy policy">
      <p>
        This policy explains how <strong>{legalConfig.operatorName}</strong> processes personal data when you use Threadmap at {legalConfig.serviceUrl}. It applies to the hosted web app, account features, notifications, file storage, and optional integrations.
      </p>

      <section>
        <h2>1. Who is responsible</h2>
        <p>
          The data controller is <strong>{legalConfig.operatorName}</strong>. Contact us at{' '}
          <a href={`mailto:${legalConfig.contactEmail}`}>{legalConfig.contactEmail}</a>.
          {legalConfig.postalAddress ? <> Postal address: {legalConfig.postalAddress}.</> : null}
        </p>
      </section>

      <section>
        <h2>2. Data we process</h2>
        <ul>
          <li><strong>Account data:</strong> email address, display name, profile image, authentication provider, and account identifiers.</li>
          <li><strong>Your workspace:</strong> tasks, notes, goals, habits, projects, events, tags, settings, links, and files you choose to upload.</li>
          <li><strong>Device and notification data:</strong> local app preferences, push subscription identifiers, timezone, and notification schedules.</li>
          <li><strong>Optional integrations:</strong> Google Calendar event titles, descriptions, dates and times, recurrence and status information, event identifiers, and sync state when you enable browser calendar synchronization; MCP authorization records when you connect an AI client; and an encrypted Google refresh credential, connected-account email address, granted scopes, and on-demand Gmail, Google Calendar, or Google Drive results when you separately connect Google Workspace for Threadmap Secretary. Browser calendar synchronization continues to hold its short-lived access token in account-scoped browser session storage.</li>
          <li><strong>Product lookup data:</strong> product names, search terms, and public product URLs you submit when you ask Threadmap to find item details, images, or prices.</li>
          <li><strong>Operational data:</strong> IP address, browser and request metadata, error information, security events, and service logs generated by our hosting and cloud providers.</li>
        </ul>
      </section>

      <section>
        <h2>3. Why we process it</h2>
        <ul>
          <li>To provide, synchronize, secure, support, and improve the service under our contract with you.</li>
          <li>To prevent abuse, investigate failures, and protect accounts and infrastructure based on our legitimate interests in running a safe service.</li>
          <li>To operate optional notifications or third-party integrations at your request. You can disconnect those integrations at any time.</li>
          <li>To comply with legal obligations and respond to valid legal requests where required.</li>
        </ul>
      </section>

      <section>
        <h2>4. Service providers and transfers</h2>
        <p>
          Threadmap currently relies on Google Firebase and Google Cloud for authentication, database, storage, functions, and notifications, on Vercel for web hosting and delivery, and on Resend for transactional authentication email. Optional integrations send data to the provider you choose, such as Google Calendar or your MCP client. These companies process data under their own terms and applicable data-processing agreements. Depending on your location, processing can involve an international transfer protected by contractual or other lawful safeguards.
        </p>
        <p>
          When you use product lookup, Threadmap&apos;s server sends the product URL to that public website or sends your product search terms to configured search providers, which can include Google, Bing, and DuckDuckGo. Do not include private or sensitive information in a product name, search term, or URL.
        </p>
        <p>
          If you save or display an image hosted by another website, your browser requests that image from its host. The host can receive ordinary connection data such as your IP address and browser metadata; Threadmap suppresses the Threadmap referrer on these image requests.
        </p>
        <p>
          When you authorize an MCP client, it receives only the scopes you approve. The client can request owner-scoped Threadmap records and, if you separately connected Google Workspace and approved the <code>workspace.read</code> scope, bounded Gmail, Google Calendar, or Google Drive results through those tools. Data selected by a tool call can also be processed by the client and any model provider you chose there. Google credentials are never returned to the client. Threadmap does not send workspace content to a first-party model provider on its own. Permanent deletion through MCP requires a separate preview and short-lived confirmation step.
        </p>
        <p>
          Browser calendar synchronization uses Google Calendar information only for the user-facing synchronization you request. Google-connected or Google-derived copies inside Threadmap remain excluded from Threadmap item tools. If you separately connect Google Workspace for Threadmap Secretary, the server obtains short-lived access tokens from an encrypted refresh credential and reads Gmail, Calendar, or Drive only when an authorized client calls the relevant read tool. Threadmap&apos;s use of information received from Google Workspace APIs adheres to the <a href="https://developers.google.com/workspace/workspace-api-user-data-developer-policy">Google Workspace API User Data and Developer Policy</a>, including its Limited Use requirements.
        </p>
        <p>We do not sell personal data and do not use your workspace content for advertising.</p>
      </section>

      <section>
        <h2>5. Cookies and local storage</h2>
        <p>
          Threadmap uses browser storage and authentication state that are necessary to keep you signed in, support offline use, remember preferences, prevent conflicts, and synchronize your workspace. The current product does not install advertising cookies or non-essential behavioral analytics cookies. If that changes, this policy and any required consent controls will be updated before those tools are enabled.
        </p>
      </section>

      <section>
        <h2>6. Retention and deletion</h2>
        <p>
          Workspace data is retained while your account is active. You can export your account data and request account deletion from Settings. Deletion removes the authentication account, owned database records, uploaded files, notification registrations, and Threadmap-held integration authorization records through a server-controlled deletion process. To stop a deleted account from being recreated by an already-issued session or delayed upload, a minimal server-only deletion marker—its document identifier and completion time—is scheduled to expire 180 days after deletion completes and is normally removed by the managed database TTL process shortly afterward. Operational and security logs are normally retained for 30 days. Encrypted recovery backups use a seven-day daily and 28-day weekly retention window, so deleted records can remain in protected backups until those copies rotate out. A longer hold applies only where law requires it.
        </p>
        <p>
          Disconnecting the server-side Google Workspace integration attempts provider revocation and always deletes Threadmap&apos;s stored encrypted refresh credential. Account deletion also removes that credential and all pending Google authorization state. Browser calendar synchronization attempts to revoke a usable browser token during its own disconnect flow. If provider revocation cannot be confirmed, remove Threadmap from the third-party access controls in your Google Account to ensure Google-held consent is withdrawn.
        </p>
      </section>

      <section>
        <h2>7. Security</h2>
        <p>
          We use encrypted transport, managed authentication, optional authenticator-app two-factor authentication, per-account database and storage rules, restricted server credentials, bounded uploads, and abuse controls. No online service can guarantee absolute security. Please use a unique password and report suspected vulnerabilities through our <a href="/security">security page</a>.
        </p>
      </section>

      <section>
        <h2>8. Your rights</h2>
        <p>
          Depending on applicable law, you may request access, correction, deletion, restriction, objection, or portability of your personal data, and you may complain to your local supervisory authority. Use the export and deletion tools in Settings or email <a href={`mailto:${legalConfig.contactEmail}`}>{legalConfig.contactEmail}</a>. We may need to verify that the request belongs to you.
        </p>
      </section>

      <section>
        <h2>9. Children and changes</h2>
        <p>
          Threadmap is not directed to children under 16. We may update this policy when the product, providers, or law changes. Material changes will be presented in the app or through another appropriate notice.
        </p>
      </section>
    </LegalPage>
  );
}
