import type { Metadata } from 'next';

import { LegalPage } from '@/components/legal/legal-page';
import { legalConfig } from '@/lib/legal-config';

export const metadata: Metadata = {
  title: 'Privacy Policy | Threadmap',
  description: 'How Threadmap collects, uses, protects, and deletes personal data.',
};

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="Your data" title="Privacy policy">
      <p>
        This policy explains how <strong>{legalConfig.operatorName}</strong> processes personal data when you use Threadmap at {legalConfig.serviceUrl}. It applies to the hosted web app, account features, notifications, file storage, and optional integrations.
      </p>

      <section>
        <h2>1. Who is responsible</h2>
        <p>
          The data controller is <strong>{legalConfig.operatorName}</strong>. Contact us at{' '}
          <a href={`mailto:${legalConfig.contactEmail}`}>{legalConfig.contactEmail}</a>.
          {legalConfig.postalAddress ? <> Postal address: {legalConfig.postalAddress}.</> : null}
        </p>
      </section>

      <section>
        <h2>2. Data we process</h2>
        <ul>
          <li><strong>Account data:</strong> email address, display name, profile image, authentication provider, and account identifiers.</li>
          <li><strong>Your workspace:</strong> tasks, notes, goals, habits, projects, events, tags, settings, links, and files you choose to upload.</li>
          <li><strong>Device and notification data:</strong> local app preferences, push subscription identifiers, timezone, and notification schedules.</li>
          <li><strong>Optional integrations:</strong> calendar identifiers and sync state when you connect Google Calendar, and authorization records when you connect an MCP client.</li>
          <li><strong>Operational data:</strong> IP address, browser and request metadata, error information, security events, and service logs generated by our hosting and cloud providers.</li>
        </ul>
      </section>

      <section>
        <h2>3. Why we process it</h2>
        <ul>
          <li>To provide, synchronize, secure, support, and improve the service under our contract with you.</li>
          <li>To prevent abuse, investigate failures, and protect accounts and infrastructure based on our legitimate interests in running a safe service.</li>
          <li>To operate optional notifications or third-party integrations at your request. You can disconnect those integrations at any time.</li>
          <li>To comply with legal obligations and respond to valid legal requests where required.</li>
        </ul>
      </section>

      <section>
        <h2>4. Service providers and transfers</h2>
        <p>
          Threadmap currently relies on Google Firebase and Google Cloud for authentication, database, storage, functions, and notifications, and on Vercel for web hosting and delivery. Optional integrations send data to the provider you choose, such as Google Calendar or your MCP client. These companies process data under their own terms and applicable data-processing agreements. Depending on your location, processing can involve an international transfer protected by contractual or other lawful safeguards.
        </p>
        <p>We do not sell personal data and do not use your workspace content for advertising.</p>
      </section>

      <section>
        <h2>5. Cookies and local storage</h2>
        <p>
          Threadmap uses browser storage and authentication state that are necessary to keep you signed in, support offline use, remember preferences, prevent conflicts, and synchronize your workspace. The current product does not install advertising cookies or non-essential behavioral analytics cookies. If that changes, this policy and any required consent controls will be updated before those tools are enabled.
        </p>
      </section>

      <section>
        <h2>6. Retention and deletion</h2>
        <p>
          Workspace data is retained while your account is active. You can export your account data and request account deletion from Settings. Deletion removes the authentication account, owned database records, uploaded files, notification registrations, and active integration authorization records through a server-controlled deletion process. Limited security, legal, or backup records may remain where required and are removed according to provider and legal retention schedules.
        </p>
      </section>

      <section>
        <h2>7. Security</h2>
        <p>
          We use encrypted transport, managed authentication, per-account database and storage rules, restricted server credentials, bounded uploads, and abuse controls. No online service can guarantee absolute security. Please use a unique password and report suspected vulnerabilities through our <a href="/security">security page</a>.
        </p>
      </section>

      <section>
        <h2>8. Your rights</h2>
        <p>
          Depending on applicable law, you may request access, correction, deletion, restriction, objection, or portability of your personal data, and you may complain to your local supervisory authority. Use the export and deletion tools in Settings or email <a href={`mailto:${legalConfig.contactEmail}`}>{legalConfig.contactEmail}</a>. We may need to verify that the request belongs to you.
        </p>
      </section>

      <section>
        <h2>9. Children and changes</h2>
        <p>
          Threadmap is not directed to children under 16. We may update this policy when the product, providers, or law changes. Material changes will be presented in the app or through another appropriate notice.
        </p>
      </section>
    </LegalPage>
  );
}
